default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  prepared_statements: false
#  statement_limit: 50

development:
  <<: *default
  database: nortex_test_db
  username: api_db_user
  password: P@ssw0rd

test:
  <<: *default
  database: nortex_test_db
  username: api_db_user
  password: P@ssw0rd

production:
  <<: *default
  database: nortex_test_db
  username: api_db_user
  password: P@ssw0rd
